/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-10-11 20:18:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FormulaireInscription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<b style=\"color: red;\"> ");

 	String message = (String) request.getAttribute("m");
 	if (message != null) {

 		out.print(message);
 	}
 
      out.write("\r\n");
      out.write("\t</b>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"TraiteInscription\" method=\"post\">\r\n");
      out.write("\t\t<h3 style=\"float: right; padding-right: 300px;\">Demande formation\r\n");
      out.write("\t\t\tphp</h3>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<caption style=\"float: left; font-weight: bold;\">Vos\r\n");
      out.write("\t\t\t\tinformations:</caption>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.print("<br>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.print("<br>");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>Civilité</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" name=\"civilite\" value=\"Mme\">Mme</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" name=\"civilite\" value=\"Mr\">Mr</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>Nom:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"nom\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>Prénom:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"prenom\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>Tel:</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"tel\"></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>Domaine:</td>\r\n");
      out.write("\t\t\t\t<td><select name=\"domaine\">\r\n");
      out.write("\t\t\t\t\t\t<option>Informatique</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Automatique</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>Vous maitrisez HTML et CSS ?</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"question\">Oui</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"question\">Non</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<caption style=\"float: left; font-weight: bold;\">Disponibilité:</caption>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Dimanche</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"matin\">Matin</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"aprem\">Apres-midi</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Lundi</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"matin\">Matin</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"aprem\">Apres-midi</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Mardi</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"matin\">Matin</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"aprem\">Apres-midi</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Mercredi</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"matin\">Matin</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"aprem\">Apres-midi</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Jeudi</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"matin\">Matin</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" name=\"aprem\">Apres-midi</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Enregistrer\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
